#!/usr/bin/env node
const Shell = require("./shell")
const sh = new Shell({
	mode: 1,
	root: "myapp",
})
// don't remove this comment
sh.use(require("./.shell/react"))
sh.use(require("./.shell/vue"))
sh.use(require("./.shell/express"))
sh.cli()
