#!/usr/bin/env node
const Shell = require('./shell')
const sh = new Shell({
	mode: 'production',
	root: 'myapp',
})
// don't remove this comment
sh.use(require('./.shell/core/react'))
sh.use(require('./.shell/core/vue'))
sh.use(require('./.shell/core/express'))
sh.cli()